### ISSUE TITLE
Cannot add task in project - GLPI 0.90.1

### ISSUE THREAD

**Issue by grajek** [tomolimo/mhooks#1]
Hello!
When this plugin is active, you can't add any tasks to project in Tools/Projects menu ("You don't have permission to perform this action."). More Hooks version 1.1.0, GLPI version 0.90.1.

**Comment by tomolimo** [comment]
Hello,
Could you tell me if you have any errors in log files?
And
Could you give the list of GLPI plugins you have?
Thank you,
Tomolimo

**Comment by grajek** [comment]
Hello!
Thank you for your fast response!
Here's php-errors.log:

_Test_
_2016-02-17 10:26:21 [51@GLPILAB]_
-  **\* PHP Notice(8): Undefined index: projects_id*
-  Backtrace :*
-  inc/projecttask.class.php:360                      *
-  inc/commonglpi.class.php:464
  ProjectTask->showForm()*
-  plugins/mhooks/inc/mhooks.commonglpi.class.php:19
  CommonGLPI::plugin_mhooks_displayStandardTab_original()*
-  ajax/common.tabs.php:91
  CommonGLPI::displayStandardTab()*
  _2016-02-17 10:26:21 [51@LNXGLPI24LABD2]_
-  **\* PHP Notice(8): Undefined index: projecttasks_id*
-  Backtrace :*
-  inc/projecttask.class.php:361                      *
-  inc/commonglpi.class.php:464
  ProjectTask->showForm()*
-  plugins/mhooks/inc/mhooks.commonglpi.class.php:19
  CommonGLPI::plugin_mhooks_displayStandardTab_original()*
-  ajax/common.tabs.php:91
  CommonGLPI::displayStandardTab()*

And here is the list of installed plugins:

Alerts 0.90-1.0 Enabled
Appliances 2.0.0 Enabled
Behaviours 0.90 Enabled
Dashboard 0.7.1 Installed / not activated
Forms 0.90-1.3.3 Enabled
Lock 3.2.0 Installed / not activated
More Hooks 1.1.0 Enabled
OCS Inventory NG 1.2.1 Enabled
Orders management 0.85+1.1 Enabled
Web Services 1.6.0 Enabled

Thanks!
Arkadiusz

2016-02-15 13:41 GMT+01:00 tomolimo notifications@github.com:

**Comment by tomolimo** [comment]
Hello,
Two things:
1. mhooks is needed for lock, but lock is not currently completely compatible with 0.90, so you may deactivate mhooks
2. you may try the latest version of mhooks: https://github.com/tomolimo/mhooks/releases/tag/1.2.0

regards
Tomolimo

**Comment by grajek** [comment]
OK, are you planning to work with Lock compatibility with v. 0.90? - it's
the Lock I'm mostly interested in...I will of course try newest version of
Mhooks though.

Keep up good work! In my company lock mechanism is extremely useful!

Regards

A.

2016-02-17 10:48 GMT+01:00 tomolimo notifications@github.com:

**Comment by tomolimo** [comment]
Please see 'readme': https://github.com/tomolimo/lock

**Comment by grajek** [comment]
OK, checked version 1.2.0 of mhooks and it's working fine.

 Thank you!

A.

2016-02-17 11:43 GMT+01:00 tomolimo notifications@github.com:
